config/routes.rb
Rails.application.routes.draw do
  resources :trees
  get "home/index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  get "home/pricing"
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users, controllers: {
    registrations: "users/registrations"
  }

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"'
  root "home#index"

  devise_scope :user do
    get "/users/sign_out" => "devise/sessions#destroy"
  end
end

app/views/layouts/_navbar.html.erb
<%= stylesheet_link_tag "navbar" %>

<div class="navbar">
  <div class="navbar-brand">
    <%= link_to image_tag("trees.png", alt: "Logo", style: "width: 40px; color:green;"), home_index_path %>
  </div>

  <div class="navbar-links">
    <%= link_to "Pricing", home_pricing_path, class: "nav-link" %>
    <% if user_signed_in? %>
      <div class="navbar-user">
       <%= link_to "My Account", edit_user_registration_path, class:"nav-link"%>
      <%= link_to "Sign out", destroy_user_session_path,class:"nav-link", style:"border:none;"%>
      </div>
    <% else %>
      <div class="navbar-auth">
        <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Linktreeclone" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "layouts/navbar"%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>